### ISSUE TITLE
Circuit and board

### ISSUE THREAD

**Issue by jesusjk143** [Zambu1/Overwatch_GPU#2]
I bought two leonardo Pro micro and copied the circuit you made.

But I don't understand the video, is the second card you use an internet card?

if I use the two leonardo micro board, it doesn't work?

Can you help me?

https://imgur.com/MPkIj63

Discord: Cebola#4030

**Comment by Nuxar1** [comment]
The setup you have in the image looks to be correct. Not just upload the sender and receiver code to the chips and connect them accordingly. Lastly start the RAW_ClientMouse program on the 2nd pc with the mouse and sender connected to it.
