### ISSUE TITLE
arduino+usb host shiled how to use this

### ISSUE THREAD

**Issue by ranchen421** [Zambu1/Overwatch_GPU#4]
arduino+usb host shiled how to use this

**Comment by Nuxar1** [comment]
Figure out how to read data from the host shield and add the mouse movement to the movement sent by the host pc.

**Comment by ranchen421** [comment]
you are using the second arduino to read the mouse of the second pc, if i have a usb shiled, then i just read the pc cursor directly

**Comment by Nuxar1** [comment]
Just replace the second pc and Arduino with your host shield and get your mouse's movement that way. You'll need to do that yourself though, I won't give you a source to copy and paste that.

**Comment by ranchen421** [comment]
code to implement aim do i need to write to arduino?

**Comment by ranchen421** [comment]
> 只需将第二台 pc 和 Arduino 替换为您的主机防护罩，然后以这种方式移动鼠标即可。你需要自己做，我不会给你复制和粘贴的来源。

No problem, I've done this step
